# Generated by Django 2.2.5 on 2019-11-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PagVenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': (('admin', 'Es admin'), ('cliente', 'Es cliente'))},
        ),
    ]
