# Generated by Django 2.2.5 on 2019-11-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PagVenta', '0002_auto_20191104_1141'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
    ]
