# Generated by Django 2.2.5 on 2019-11-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagVenta', '0004_datos_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.TextField(default=''),
        ),
    ]
