# Generated by Django 2.2.5 on 2019-12-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagVenta', '0005_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image_file',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
