# Generated by Django 2.2.5 on 2019-12-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PagVenta', '0006_auto_20191204_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='image_url',
        ),
    ]
